In [1]:
import numpy as np

In [4]:
# Numpy Provides
"""
Extension package to python for multi-dimensional arrays
Closer to hardware(Efficiency)
Designed for Scientific computation ( Convience)
Also known as array oriented Computing
"""
# Numpy Array
a=np.array([5,6,7,3,5])
print(a)
print(np.arange(10))

[5 6 7 3 5]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
# Why Numpy Array is Useful
    #Memory Efficient Container
    # Fast Numerical operations

#python list
l=range(1000)    
%timeit [i**2 for i in l]

446 µs ± 24.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
#Numpy array
a=np.arange(1000)
%timeit a**2

3.11 µs ± 183 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
# Here list is 200 times slower than nparray

In [18]:
#np methods

a=np.arange(10)
print(a)
print(a.ndim) #returns the dimension of array
print(a.shape) # size (of matrix or...)
print(len(a)) # no. of rows
print() # for an empty line
#2-d array
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim) #returns the dimension of array
print(b.shape) # size (of matrix or...)
print(len(b))
print()
#2-d array
c=np.array([[[0,2,3],[3,5,6]],[[6,7,8],[9,1,2]]])
print(c)
print(c.ndim) #returns the dimension of array
print(c.shape) # size (of matrix or...)
print(len(c))


[0 1 2 3 4 5 6 7 8 9]
1
(10,)
10

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2

[[[0 2 3]
  [3 5 6]]

 [[6 7 8]
  [9 1 2]]]
3
(2, 2, 3)
2


In [21]:
# np methods
    #arange(start,end(excluded),step)
x=np.arange(1,10,2)
print(x)
#linspace(linear space)  #it divides the [0,1] into n equals interval
y=np.linspace(0,10,6) #start, end ,no of points
print(y)

[1 3 5 7 9]
[ 0.  2.  4.  6.  8. 10.]


In [25]:
g=np.ones((3,3)) #takes arguments as tuple 
g 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
np.eye(4,3) # create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [32]:
d=np.diag([1,2,3,4]) #create a diagonal matrix of given value in the form of LIST
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
np.diag(d) #extraction of diagonal elem for diag matrix

array([1, 2, 3, 4])

In [36]:
a=np.random.rand(4)
a

array([0.80008097, 0.67469748, 0.36508185, 0.96060987])

In [37]:
np.random.randn(4)

array([ 0.42845894,  0.53556407,  0.13150768, -0.39008834])

In [43]:
# Different Datatypes in numpy
"""
int64 #64 no. represent size only 
float64 #default for zeros and ones
complex128
boolean
s6 #string
i #signed int 
u #unsigned int
M #dateime
V #raw data(void)

"""

'\nint64 #64 no. represent size only \nfloat64 #default for zeros and ones\ncomplex128\nboolean\ns6 #string\ni #signed int \nu #unsigned int\nM #dateime\nV #raw data(void)\n\n'

In [47]:
#Indexing and Slicing is same as list 
a=np.arange(10)
b=a[::2]  #slicing make view of same memory 
print(a,b)
print(np.shares_memory(a,b))
b[0]=5
print(a)

# numpy share memory for slicing for memory efficient so due to same memory location if sliced var changed
# then the change deflect on original array also.

# to make a force full copy we use
c=a[::2].copy()
print(c)
print(np.shares_memory(a,c)) #it does share same memory

[0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]
True
[5 1 2 3 4 5 6 7 8 9]
[5 2 4 6 8]
False


In [52]:
# Ques assign all even value to -1 in an array
    #To do so we use fancy indexing also called (Masks) 
    # it creates copy not views
arr=np.arange(15)
print(arr)

mask= arr%2==0
extract_from_arr = arr[mask]
print(extract_from_arr)
arr[extract_from_arr]=-1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14]
[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1]


In [58]:
#operation done in Elementwise operation

print(a)
a[1]=11
print(a.max())
print(a.argmax()) # returns index of max element

a.mean()

[ 5 11  2  3  4  5  6  7  8  9]
11
1


6.0

In [65]:
a=np.arange(0,40,10)
t=np.tile(a,(3,2)) #to place an array as a tile over and over 3 times (row) and 2 times of it 
print(t)
print(t.shape)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
(3, 8)


In [91]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
r=a.ravel() #return a contiguous flattened array
print(r)
print(a.T)
print(a.T.ravel())
print()
print(a)
b=a.reshape(4,2) #Opposite of ravel
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 5 2 6 3 7 4 8]

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [92]:
#resize to definite size
a=np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [98]:
#sorting data
a=np.array([[3,4,5,6],[9,8,7,6]])
print(a)
b=np.sort(a,axis=1)
print(b)

print()
a=np.array([3,2,1,6])
print(a)
print()
j=np.argsort(a) # return index in sorted order of array value
print(j)
a[j]

[[3 4 5 6]
 [9 8 7 6]]
[[3 4 5 6]
 [6 7 8 9]]

[3 2 1 6]

[2 1 0 3]


array([1, 2, 3, 6])